name: gen_transport

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@main
              
            - name: generate transport pages
              run: make -C trans
